version: "3.6"

services:
  postgres:
    container_name: hasura_postgres
    image: postgres:12.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db-dumps:/db-dumps
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    command:
      - "postgres"
  graphql-engine:
    container_name: hasura_console
    image: hasura/graphql-engine:latest
    ports:
      - "8082:8080"
    volumes:
      - ./migrations:/migrations
    depends_on:
      - "postgres"
    environment:
      GHCRTS: "-M768m"
      HASURA_GRAPHQL_ADMIN_SECRET: local
      HASURA_GRAPHQL_DATABASE_URL: postgresql://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
    restart: always
